Source files for LatinR data.table tutorial slides

Title: Using and contributing to the data.table package for efficient big data analysis

Link: http://r-datatable.com

Abstract: data.table is one of the most efficient open-source
in-memory data manipulation packages available today. First released
to CRAN by Matt Dowle in 2006, it continues to grow in popularity, and
now over 1500 other CRAN packages depend on data.table. 
This talk will start with data reading from CSV, discuss basic and
advanced data manipulation topics, and finally will end with a
discussion about how you can contribute to data.table.

** English

[[https://docs.google.com/presentation/d/1ypW1LUMmcrUTMF6B9h9s8qbvW5BSbN1IW6CEgqX01Co/edit?usp=sharing][Original google slides Oct 2023]],
[[https://docs.google.com/presentation/d/1mHTFR6Eg7OdKi6yJcAvMk5_B8hjtMmsczs8Ewxt2xT8/edit#slide=id.p1][revised slides Aug 2024]],
by Toby Dylan Hocking.

Source code for figures:

[[file:figure-roll.R]] explains rolling join.

[[file:figures-iris-dt/]] contains source files for melt conceptual
figures, adapted from [[https://github.com/tdhock/nc-article/blob/master/figure-1-iris.svg][nc article]]. SVG files use Courier and Sans fonts.

[[file:figure-melt-exercises.R]] contains code for melt exercise figures.

** Español
Fuentes código y gráficos:

[[file:latindatatransforme-vspanish-.pdf]] Presentación en Español adaptación presentación de Toby Dylan Hocking en LatinR

[[file:latinrdatatransforme_spanish.qmd]] contiene el código en reveal js (.qmd) de la presentación. Se complementa con las imagenes de la carpeta images.

[[file:images/]] contiene las imágenes usadas en latinrdatatransforme_spanish.qmd

[[file:figure-melt-exercises_vm.R]] contiene código para el ejercicio gráfico de melt con datos::flores. 

[[file:figure-1-iris-dt-single-2value-vespa%C3%B1ol1.svg][SVG file]] etc : contiene las imágenes para adaptar la explicación conceptual para melt proveniente de
[[https://github.com/tdhock/nc-article/blob/master/figure-1-iris.svg][nc article]].

Nota: Para los archivos fuente svg, la fuente que use fue Sans.



