* Source files for data.table tutorial slides

** English

Title: Using and contributing to the data.table package for efficient big data analysis

Package documentation: http://r-datatable.com

Links to tutorial source code and slides: https://github.com/tdhock/2023-10-LatinR-data.table

Abstract: data.table is one of the most efficient open-source
in-memory data manipulation packages available today. First released
to CRAN by Matt Dowle in 2006, it continues to grow in popularity, and
now over 1500 other CRAN packages depend on data.table. 
This talk will start with data reading from CSV, discuss basic and
advanced data manipulation topics, and finally will end with a
discussion about how you can contribute to data.table.

Installation instructions for participants: any version of R should work. I typically use the most recent release version. Make sure you can =install.packages("data.table")= and that should be all!

[[https://docs.google.com/presentation/d/1ypW1LUMmcrUTMF6B9h9s8qbvW5BSbN1IW6CEgqX01Co/edit?usp=sharing][Original google slides Oct 2023]],
[[https://docs.google.com/presentation/d/1mHTFR6Eg7OdKi6yJcAvMk5_B8hjtMmsczs8Ewxt2xT8/edit#slide=id.p1][revised slides Aug 2024]],
by Toby Dylan Hocking.

Source code for figures:

[[file:figure-roll.R]] explains rolling join.

[[file:figures-iris-dt/]] contains source files for melt conceptual
figures, adapted from [[https://github.com/tdhock/nc-article/blob/master/figure-1-iris.svg][nc article]]. SVG files use Courier and Sans fonts.

[[file:figure-melt-exercises.R]] contains code for melt exercise figures.

** français

Titre : data.table pour la traitement efficace des grands jeux de données

Documentation : http://r-datatable.com

Code source du tutoriel : https://github.com/tdhock/2023-10-LatinR-data.table

Résumé : data.table est un package R qui permet la traitement efficace des grands jeux de données. 
Il inclus des fonctions pour lecture et écriture des fichiers CSV, aggrégation, restructuration, jointure, etc.
Par rapport aux autres logiciels avec ces fonctions, 
l'utilisation de data.table peut être 10x plus efficace en temps de calcul, et en utilisation de mémoire.
Sur CRAN depuis 2006, il est très utilisé, avec plus de 1500 autres packages qui en dépend.
Ce tutoriel va discuter : son efficacité rélatif aux autres packages (tidyverse, pandas, etc),
l'utilisation du package (fonctions de base et avancées),
une discussion de comment écrire un package qui dépend de data.table,
ainsi que quelques remarques sur la communauté de développeurs de data.table, 
qui est très ouverte aux contributions du public. 

Installation : il va y avoir quelques exercises pour les participants.
SVP inste
qui devraient

Installation instructions for participants: any version of R should work. I typically use the most recent release version. Make sure you can =install.packages("data.table")= and that should be all!

** Español
Fuentes código y gráficos:

[[file:latindatatransforme-vspanish-.pdf]] Presentación en Español adaptación presentación de Toby Dylan Hocking en LatinR

[[file:latinrdatatransforme_spanish.qmd]] contiene el código en reveal js (.qmd) de la presentación. Se complementa con las imagenes de la carpeta images.

[[file:images/]] contiene las imágenes usadas en latinrdatatransforme_spanish.qmd

[[file:figure-melt-exercises_vm.R]] contiene código para el ejercicio gráfico de melt con datos::flores. 

[[file:figure-1-iris-dt-single-2value-vespa%C3%B1ol1.svg][SVG file]] etc : contiene las imágenes para adaptar la explicación conceptual para melt proveniente de
[[https://github.com/tdhock/nc-article/blob/master/figure-1-iris.svg][nc article]].

Nota: Para los archivos fuente svg, la fuente que use fue Sans.



